### ISSUE TITLE
and_yet_it_hurt.exe file is missing

### ISSUE THREAD

**Issue by cytek04** [Sheepolution/explorer#2]
"Unzip all files in a folder and start and_yet_it_hurt.exe.", but there is no file with that name. Do I need to compile it myself? And if so, how?

**Comment by Sheepolution** [comment]
It should be there. It might be that your virus scanner removed the file because it deemed it to be dangerous (which it's not).

![image](https://user-images.githubusercontent.com/2232780/204934965-76aa9522-ed78-4860-8010-5885b02eda55.png)
